### ISSUE TITLE
2 issues in the project

### ISSUE THREAD

**Issue by itsharshdeep** [ashblue/unity-skill-tree-editor#1]
As I downloaded the package there were 2 issues present ( no any console errors).
1. Skill tree Editor window is not opening. I mean the window is blank
2. When you will run the scene "MultipleSkillTrees" . You will get the error. Please let us know that which node I need to assign there.

**Comment by itsharshdeep** [comment]
I have resolved/find the steps to resolve the issue (1.) if anybody else is struggling ( or in future if any noob (like me) come here) 

1. Dock/Open the skill tree window by going to the Window>Skill Tree
2. Open the scene "BasicSkillTree" or "MultipleSkillTrees" 
3. If you opened "MultipleSkillTrees" Scene. Then select the GameObject "SkillTreeData">"SkillTreeData3" ( you can select any 3/2/1)
4. If you opened "BasicSkillTree" Scene. Then select the GameObject "SkillTreeExample"
5. As you select the gameObjet ( any of the above described ), you will see the skill window refresh itself and all data appears.
6. You can right click on the empty space. or you can also right click on the Node(if already present).
7. For switching the skill category you need to select the category on top right side of the 'Skill Tree' Window.

Hope thats help. 
Thanks a lot to Ash for creating & make this useful product available to all of us.
I'm still looking for the '2.' issues as I came up with any solution. I'll update this. 

Thanks a lot 
Harshdeep S

**Comment by itsharshdeep** [comment]
To resolve the issue no '2' i.e. "When you will run the scene "MultipleSkillTrees". You will get the error. Please let us know that which node I need to assign there"

Go the 'Skill Menu' script & provide any size to the 'Cell size' which was previously 0,0

**Comment by ashblue** [comment]
Sorry I totally missed this issue (looks like a version change at some point triggered it). At some point I need to rewrite this, but have been super busy with another project. If you have a minute to push a pull request I'll merge it into the repo.

**Comment by itsharshdeep** [comment]
@ashblue : No, there wasn't any issue. I just don't know that how to correctly use the code. 
I have closed the issue and also wrote the steps in case if somebody also gets the errors like me. 

Thanks a lot for providing such a wonderful code for public use. 👍 :1st_place_medal:

**Comment by ashblue** [comment]
@itsharshdeep That's great to hear and thanks for filing a ticket. Always good to know what causes difficulties for people and how to improve in the future.
