### ISSUE TITLE
Live Demo is Down

### ISSUE THREAD

**Issue by Aki1024** [ashblue/unity-skill-tree-editor#2]
If you lack a permanent hosting solution, I can host a mirror on my website.

**Comment by ashblue** [comment]
It probably got taken down by Dropbox. I'll probably have to re-create a new public link. I'm working on a new API that creates a skill tree editor from passed data. Much better than the example solution here. It's a work in progress though. Thanks for bringing this to my attention 😄

**Comment by ashblue** [comment]
Closing this out since a replacement skill tree system is in the works.
